export default [
  {
    id: 1,
    name: "Expresso Tradicional",
    tags: ["Tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    price: 9.9,
    image: "Expresso.png",
  },
  {
    id: 2,
    name: "Expresso Americano",
    tags: ["Tradicional"],
    description: "Expresso diluído, menos intenso que o tradicional",
    price: 9.9,
    image: "Americano.png",
  },
  {
    id: 3,
    name: "Expresso Cremoso",
    tags: ["Tradicional"],
    description: "Café expresso tradicional com espuma cremosa",
    price: 9.9,
    image: "ExpressoCremoso.png",
  },
  {
    id: 4,
    name: "Expresso Gelado",
    tags: ["Tradicional", "Gelado"],
    description: "Bebida preparada com café expresso e cubos de gelo",
    price: 9.9,
    image: "cafeGelado.png",
  },
  {
    id: 5,
    name: "Café com Leite",
    tags: ["Tradicional", "Com leite"],
    description: "Meio a meio de expresso tradicional com leite vaporizado",
    price: 9.9,
    image: "CafecomLeite.png",
  },
  {
    id: 6,
    name: "Latte",
    tags: ["Tradicional", "Com leite"],
    description:
      "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    price: 9.9,
    image: "Latte.png",
  },
  {
    id: 7,
    name: "Capuccino",
    tags: ["Tradicional", "Com leite"],
    description:
      "Bebida com canela feita de doses iguais de café, leite e espuma",
    price: 9.9,
    image: "Capuccino.png",
  },
  {
    id: 8,
    name: "Macchiato",
    tags: ["Tradicional", "Com leite"],
    description:
      "Café expresso misturado com um pouco de leite quente e espuma",
    price: 9.9,
    image: "Macchiato.png",
  },
  {
    id: 9,
    name: "Mocaccino",
    tags: ["Tradicional", "Com leite"],
    description: "Café expresso com calda de chocolate, pouco leite e espuma",
    price: 9.9,
    image: "Mocaccino.png",
  },
  {
    id: 10,
    name: "Chocolate Quente",
    tags: ["Especial", "Com leite"],
    description: "Bebida feita com chocolate dissolvido no leite quente e café",
    price: 9.9,
    image: "ChocolateQuente.png",
  },
  {
    id: 11,
    name: "Cubano",
    tags: ["Especial", "Com leite", "Alcoólico"],
    description:
      "Drink gelado de café expresso com rum, creme de leite e hortelã",
    price: 9.9,
    image: "Cubano.png",
  },
  {
    id: 12,
    name: "Havaiano",
    tags: ["Especial"],
    description: "Bebida adocicada preparada com café e leite de coco",
    price: 9.9,
    image: "Havaiano.png",
  },
  {
    id: 13,
    name: "Árabe",
    tags: ["Especial"],
    description: "Bebida preparada com grãos de café árabe e especiarias",
    price: 9.9,
    image: "Arabe.png",
  },
  {
    id: 14,
    name: "Irlandês",
    tags: ["Especial", "alcoólico"],
    description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    price: 9.9,
    image: "Irlandes.png",
  },
];
